### ISSUE TITLE
学长是那一届的看到oj了看到福工的oj代码了

### ISSUE THREAD

**Issue by icyrain11** [axiangcoding/springboot3-demo#1]

**Comment by icyrain11** [comment]
我20软工的

**Comment by axiangcoding** [comment]
> 我20软工的

哈，我16的，哪有用issue来提问的...

**Comment by axiangcoding** [comment]
> 我20软工的

新版的oj就是我写的...

**Comment by icyrain11** [comment]
github不知道咋私信就想到用issue了哈哈哈哈哈可以加个联系方式吗

**Comment by axiangcoding** [comment]
> github不知道咋私信就想到用issue了哈哈哈哈哈可以加个联系方式吗

加我qq 305133882吧，看到回复个，我把这issue删了

**Comment by axiangcoding** [comment]
> github不知道咋私信就想到用issue了哈哈哈哈哈可以加个联系方式吗

这个仓库是我拿来放demo的，我还惊讶怎么会有人开issue

**Comment by icyrain11** [comment]
close 把收到了
